/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.perguntas;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.Random;
import java.util.Vector;
import javax.sound.midi.Sequence;
import javax.sound.midi.Sequencer;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author danny
 */
public class Principal extends javax.swing.JFrame {
 private static String nivel = "Basico";
 private int processado = 0;
 private int bonus = 0;
 private int acertos = 0;
 private int erros = 0;
 private int errosPorNivel = 0;
 private boolean podeVoltar = true;
private static String categoria="Cultura Geral";
private perguntas pergunt ;
private boolean prencherLabel=true;
private int trocouQuantasVezes=0;
private Timer t;
private String tipoDoJogo = "novo jogo";
private static java.awt.event.ActionEvent ev;
java.awt.event.MouseEvent evta;
private Random gerador = new Random();
private Vector<perguntas> lerObject = null;


Sequence currentSound;
	Sequencer player;
	String songFile;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();        
        jLabelNivel.setText("Nivel: "+nivel+"  "+jProgressBar1.getValue()+"%");
        jLabelCategoria.setText("Categoria:  "+categoria);
        lerArquivo();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBtNovoJogo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBtnSobreJogo = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelNivel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLblPergunta = new javax.swing.JLabel();
        jBtalineaB = new javax.swing.JButton();
        jBtalineaA = new javax.swing.JButton();
        jBtalineaC = new javax.swing.JButton();
        jBtalineaD = new javax.swing.JButton();
        jLabelCategoria = new javax.swing.JLabel();
        jBtnAjuda = new javax.swing.JButton();
        jBtnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnTrocaPergunta = new javax.swing.JButton();
        jLabelErros = new javax.swing.JLabel();
        jLabelAcertos = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLblPergunta1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBtalineaB1 = new javax.swing.JButton();
        jBtnTrocaPergunta1 = new javax.swing.JButton();
        jBtalineaA1 = new javax.swing.JButton();
        jBtalineaC1 = new javax.swing.JButton();
        jBtalineaD1 = new javax.swing.JButton();
        jLabelCategoria1 = new javax.swing.JLabel();
        jBtnAjuda1 = new javax.swing.JButton();
        jBtnVoltar1 = new javax.swing.JButton();
        jLabelNivel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tiva-Moz");
        setResizable(false);

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 130)); // NOI18N
        jLabel1.setText("Tiva-Moz");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/friends.png"))); // NOI18N
        jButton1.setText("  Jogar a Dois");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBtNovoJogo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtNovoJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation-hat-and-diploma.png"))); // NOI18N
        jBtNovoJogo.setText("   Novo Jogo");
        jBtNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNovoJogoActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/time.png"))); // NOI18N
        jButton3.setText("   Jogar Contra Tempo");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jBtnSobreJogo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnSobreJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings-work-tool.png"))); // NOI18N
        jBtnSobreJogo.setText("  Sobre o Jogo");
        jBtnSobreJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSobreJogoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Escuro");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton1MousePressed(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Claro");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton2MousePressed(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnSobreJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSobreJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, "card2");

        jLabelNivel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation-hat-and-diploma.png"))); // NOI18N
        jLabelNivel.setText("  Nivel Basico 10%");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLblPergunta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jBtalineaB.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jBtalineaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaBMouseClicked(evt);
            }
        });

        jBtalineaA.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jBtalineaA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaAMouseClicked(evt);
            }
        });

        jBtalineaC.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jBtalineaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaCMouseClicked(evt);
            }
        });

        jBtalineaD.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jBtalineaD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaDMouseClicked(evt);
            }
        });

        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation-hat-and-diploma.png"))); // NOI18N
        jLabelCategoria.setText("  Categoria:");

        jBtnAjuda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help_icon-icons.com_73700.png"))); // NOI18N
        jBtnAjuda.setText("Ajuda");
        jBtnAjuda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBtnAjudaFocusGained(evt);
            }
        });
        jBtnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAjudaActionPerformed(evt);
            }
        });

        jBtnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnVoltar.setText("Voltar");
        jBtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("B:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("A:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("C:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("D:");

        jBtnTrocaPergunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnTrocaPergunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help_icon-icons.com_73700.png"))); // NOI18N
        jBtnTrocaPergunta.setText("Proxima  Pergunta!");
        jBtnTrocaPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTrocaPerguntaActionPerformed(evt);
            }
        });

        jLabelErros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelErros.setText("Erros: ");

        jLabelAcertos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAcertos.setText("Acertos: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jBtnAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnVoltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtalineaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtalineaA, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jBtnTrocaPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtalineaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtalineaD, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabelErros, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtalineaB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtalineaA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtalineaD, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtalineaC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnTrocaPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErros, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, "card3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 976, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, "card4");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("A:");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLblPergunta1.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLblPergunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblPergunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("C:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("D:");

        jBtalineaB1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaB1MouseClicked(evt);
            }
        });

        jBtnTrocaPergunta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnTrocaPergunta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help_icon-icons.com_73700.png"))); // NOI18N
        jBtnTrocaPergunta1.setText("Proxima  Pergunta!");
        jBtnTrocaPergunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTrocaPergunta1ActionPerformed(evt);
            }
        });

        jBtalineaA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaA1MouseClicked(evt);
            }
        });

        jBtalineaC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaC1MouseClicked(evt);
            }
        });

        jBtalineaD1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaD1MouseClicked(evt);
            }
        });

        jLabelCategoria1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCategoria1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation-hat-and-diploma.png"))); // NOI18N
        jLabelCategoria1.setText("  Categoria:");

        jBtnAjuda1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnAjuda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help_icon-icons.com_73700.png"))); // NOI18N
        jBtnAjuda1.setText("Ajuda");
        jBtnAjuda1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBtnAjuda1FocusGained(evt);
            }
        });
        jBtnAjuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAjuda1ActionPerformed(evt);
            }
        });

        jBtnVoltar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnVoltar1.setText("Voltar");
        jBtnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltar1ActionPerformed(evt);
            }
        });

        jLabelNivel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNivel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation-hat-and-diploma.png"))); // NOI18N
        jLabelNivel1.setText("  Tempo : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("B:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabelCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jBtnAjuda1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnVoltar1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBtalineaC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtalineaA1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtalineaB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtalineaD1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jBtnTrocaPergunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAjuda1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabelCategoria1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNivel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnVoltar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtalineaB1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtalineaA1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtalineaD1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtalineaC1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jBtnTrocaPergunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, "card5");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNovoJogoActionPerformed
        tipoDoJogo="novo jogo";
        mostraTelaCategorias();
        CardLayout ver = (CardLayout)jPanel1.getLayout();
        ver.show(jPanel1, "card3"); 
        
    }//GEN-LAST:event_jBtNovoJogoActionPerformed

    private void jBtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarActionPerformed
        if(podeVoltar){
            CardLayout ver = (CardLayout)jPanel1.getLayout();
            ver.show(jPanel1, "card2");
            prencherLabel=true;
            jProgressBar1.setValue(0);
            trocouQuantasVezes=0;
            nivel = "basico";
            acertos=0;
            erros=0;
            errosPorNivel = 0;
            jPanel3.repaint();
        jPanel3.validate();
        lerArquivo();
        }else{
            int Confirm = JOptionPane.showConfirmDialog(null, "Abandonar o jogo Iniciado?", "", 2);
        if(Confirm==0){
            CardLayout ver = (CardLayout)jPanel1.getLayout();
            ver.show(jPanel1, "card2");
            prencherLabel=true;
            jProgressBar1.setValue(0);
            trocouQuantasVezes=0;
            nivel = "basico";
            acertos=0;
            erros=0;
            errosPorNivel=0;
            jPanel3.repaint();
        jPanel3.validate();
        lerArquivo();
        }
        }
    }//GEN-LAST:event_jBtnVoltarActionPerformed

    private void jBtnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAjudaActionPerformed
        JDialog d = new JDialog(new JFrame(),true);
        d.setContentPane(new Ajuda().getContentPane());
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jBtnAjudaActionPerformed

    private void jBtnTrocaPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTrocaPerguntaActionPerformed
       if(trocouQuantasVezes<=1){
          prencherLabel();
        trocouQuantasVezes+=1;
       }else{
           JOptionPane.showMessageDialog(null, "So pode trocar a pergunta,2 vezes  no mesmo nivel!");
       }
               
    }//GEN-LAST:event_jBtnTrocaPerguntaActionPerformed

    private void jBtalineaAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaAMouseClicked
        if(evt.getClickCount()==1){
            if(errosPorNivel<4){
           adicionaIcon(jBtalineaA);
        podeVoltar = false; 
        }else {
                 JOptionPane.showMessageDialog(null, "Atingiu o numero Maximo de Erros permitidos por Nivel!");
                 podeVoltar=true;
                 jBtnVoltarActionPerformed(ev);
             }}
    }//GEN-LAST:event_jBtalineaAMouseClicked

    private void jBtalineaDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaDMouseClicked
        if(evt.getClickCount()==1){
            if(errosPorNivel<4){
            adicionaIcon(jBtalineaD);
            podeVoltar = false;
        }else {
                 JOptionPane.showMessageDialog(null, "Atingiu o numero Maximo de Erros permitidos por Nivel!");
                 podeVoltar=true;
                 jBtnVoltarActionPerformed(ev);
             }}
    }//GEN-LAST:event_jBtalineaDMouseClicked

    private void jBtalineaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaCMouseClicked
        if(evt.getClickCount()==1){
            if(errosPorNivel<4){
            adicionaIcon(jBtalineaC);
            podeVoltar = false;
        }else {
                 JOptionPane.showMessageDialog(null, "Atingiu o numero Maximo de Erros permitidos por Nivel!");
                 podeVoltar=true;
                 jBtnVoltarActionPerformed(ev);
             }}
    }//GEN-LAST:event_jBtalineaCMouseClicked

    private void jBtalineaBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaBMouseClicked
         
         
         
//         File file = new File("Code_of_Princess_Turn_it_up_Boss_Battle_Theme.mid");
//			try{
//                            currentSound = MidiSystem.getSequence(file);
//			player = MidiSystem.getSequencer();
//			player.open();
//			player.setSequence(currentSound);
//			player.start();
//                        }catch (Exception ex){
//			System.out.println(ex.toString());
//		}
       
         
         
         if(evt.getClickCount()==1){
             if(errosPorNivel<4){
            adicionaIcon(jBtalineaB);
            podeVoltar = false;
        }else {
                 JOptionPane.showMessageDialog(null, "Atingiu o numero Maximo de Erros permitidos por Nivel!");
                 podeVoltar=true;
                 jBtnVoltarActionPerformed(ev);
             }}
    }//GEN-LAST:event_jBtalineaBMouseClicked

    private void jBtnAjudaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBtnAjudaFocusGained
       if(prencherLabel){
           prencherLabel();
       }
       jLabelCategoria.setText("Categoria:  "+categoria);
       jLabelNivel.setText("Nivel: "+nivel+"  "+jProgressBar1.getValue()+"%");
       prencherLabel=false;       
    }//GEN-LAST:event_jBtnAjudaFocusGained

    private void jBtnSobreJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSobreJogoActionPerformed
        JDialog d = new JDialog(new JFrame(),true);
        d.setContentPane(new Ajuda().getContentPane());
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jBtnSobreJogoActionPerformed

    private void jBtalineaB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaB1MouseClicked
        if(evt.getClickCount()==1){
           adicionaIcon(jBtalineaB1);
        podeVoltar = false; 
        }
    }//GEN-LAST:event_jBtalineaB1MouseClicked

    private void jBtnTrocaPergunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTrocaPergunta1ActionPerformed
        jBtnTrocaPerguntaActionPerformed(evt);
    }//GEN-LAST:event_jBtnTrocaPergunta1ActionPerformed

    private void jBtalineaA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaA1MouseClicked
        if(evt.getClickCount()==1){
           adicionaIcon(jBtalineaA1);
        podeVoltar = false; 
        }
    }//GEN-LAST:event_jBtalineaA1MouseClicked

    private void jBtalineaC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaC1MouseClicked
        if(evt.getClickCount()==1){
           adicionaIcon(jBtalineaC1);
        podeVoltar = false; 
        }
    }//GEN-LAST:event_jBtalineaC1MouseClicked

    private void jBtalineaD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaD1MouseClicked
       if(evt.getClickCount()==1){
           adicionaIcon(jBtalineaD1);
        podeVoltar = false; 
        }
    }//GEN-LAST:event_jBtalineaD1MouseClicked

    private void jBtnAjuda1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBtnAjuda1FocusGained
        jBtnAjudaFocusGained(evt);
        jProgressBar2.setValue(50);
        jPanel5.validate();
        jPanel5.repaint();
        temporizador();
    }//GEN-LAST:event_jBtnAjuda1FocusGained

    private void jBtnAjuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAjuda1ActionPerformed
        jBtnAjudaActionPerformed(evt);
    }//GEN-LAST:event_jBtnAjuda1ActionPerformed

    private void jBtnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltar1ActionPerformed
        jBtnVoltarActionPerformed(evt);
        
    }//GEN-LAST:event_jBtnVoltar1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
JOptionPane.showMessageDialog(null , "Indisponivel !");
//        nivel = "medio";
//        tipoDoJogo="Contra tempo";
//        mostraTelaCategorias();
//        CardLayout ver = (CardLayout)jPanel1.getLayout();
//        ver.show(jPanel1, "card5"); 
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      tipoDoJogo="A Dois";
      Principal1 d = new Principal1();
       d.setVisible(true);
       d.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
         String tema14="com.jtattoo.plaf.hifi.HiFiLookAndFeel";
    try {
        UIManager.setLookAndFeel(tema14);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Falha ao Aplicar o Tema: "+ex);
    }
      Principal d = new Principal();
       d.setVisible(true);
       d.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       String tema14="com.jtattoo.plaf.graphite.GraphiteLookAndFeel";
    try {
        UIManager.setLookAndFeel(tema14);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Falha ao Aplicar o Tema: "+ex);
    }
    Principal d = new Principal();
       d.setVisible(true);
       d.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2MousePressed

    private void jRadioButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         String tema2="com.jtattoo.plaf.noire.NoireLookAndFeel";
         String tema5="com.jtattoo.plaf.mint.MintLookAndFeel";
         String tema9="com.jtattoo.plaf.acryl.AcrylLookAndFeel";
         String tema10="com.jtattoo.plaf.hifi.HiFiLookAndFeel";
         String tema13="com.jtattoo.plaf.fast.FastLookAndFeel";
         String tema14="com.jtattoo.plaf.graphite.GraphiteLookAndFeel";
        try {
            UIManager.setLookAndFeel(tema14);
        } catch (Exception e) {

        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       /* Create and display the form */
 
 
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtNovoJogo;
    private javax.swing.JButton jBtalineaA;
    private javax.swing.JButton jBtalineaA1;
    private javax.swing.JButton jBtalineaB;
    private javax.swing.JButton jBtalineaB1;
    private javax.swing.JButton jBtalineaC;
    private javax.swing.JButton jBtalineaC1;
    private javax.swing.JButton jBtalineaD;
    private javax.swing.JButton jBtalineaD1;
    private javax.swing.JButton jBtnAjuda;
    private javax.swing.JButton jBtnAjuda1;
    private javax.swing.JButton jBtnSobreJogo;
    private javax.swing.JButton jBtnTrocaPergunta;
    private javax.swing.JButton jBtnTrocaPergunta1;
    private javax.swing.JButton jBtnVoltar;
    private javax.swing.JButton jBtnVoltar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAcertos;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelCategoria1;
    private javax.swing.JLabel jLabelErros;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelNivel1;
    private javax.swing.JLabel jLblPergunta;
    private javax.swing.JLabel jLblPergunta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables

     void mostraTelaCategorias() {
        categorias c = new categorias();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }
       public static void setCategoria(String categoria) {
            Principal.categoria = categoria;
         
       }
           public void lerArquivo() {      
          
        try {
            FileInputStream arquivo = new FileInputStream("perguntas.arq");
            ObjectInputStream objecto = new ObjectInputStream(arquivo);
            lerObject = (Vector<perguntas>) objecto.readObject();
            arquivo.close();
            objecto.close();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null," Erro de Leitura da Pergunta: "+erro.getMessage());   
        }
       

    }
         
      public perguntas atualizaPergunta() {
//          Random gerador = new Random();
//          Vector<perguntas> lerObject = null;

          perguntas pergunta ;
//        try {
//            FileInputStream arquivo = new FileInputStream("perguntas.arq");
//            ObjectInputStream objecto = new ObjectInputStream(arquivo);
//            lerObject = (Vector<perguntas>) objecto.readObject();
//            arquivo.close();
//            objecto.close();
//        } catch (Exception erro) {
//            JOptionPane.showMessageDialog(null," Erro de Leitura da Pergunta: "+erro.getMessage());   
//        }
int i = gerador.nextInt(lerObject.size());
        pergunta = lerObject.get(i);
        if(/*pergunta.getCategoria().equalsIgnoreCase(categoria)&*/pergunta.getNivel().equalsIgnoreCase(nivel)&&pergunta.getProcessada()==0){
        lerObject.get(i).setProcessada(1);
            return pergunta;
        }
     return atualizaPergunta();

    }
      
      
      public  void prencherLabel(){
           pergunt = atualizaPergunta();
           Random gerador = new Random();
           int n = gerador.nextInt(4);
            
           if(n==0){
            jBtalineaA.setText(pergunt.getOpcaoD());
            jBtalineaB.setText(pergunt.getOpcaoA());
            jBtalineaC.setText(pergunt.getOpcaoB());
            jBtalineaD.setText(pergunt.getOpcaoC());
            jLblPergunta.setText(pergunt.getPergunta());
           }
           if(n==1){
            jBtalineaA.setText(pergunt.getOpcaoA());
            jBtalineaB.setText(pergunt.getOpcaoD());
            jBtalineaC.setText(pergunt.getOpcaoB());
            jBtalineaD.setText(pergunt.getOpcaoC());
            jLblPergunta.setText(pergunt.getPergunta());
           }
           if(n==2){
            jBtalineaA.setText(pergunt.getOpcaoA());
            jBtalineaB.setText(pergunt.getOpcaoB());
            jBtalineaC.setText(pergunt.getOpcaoD());
            jBtalineaD.setText(pergunt.getOpcaoC());
            jLblPergunta.setText(pergunt.getPergunta());
           }
           if(n==3){
            jBtalineaA.setText(pergunt.getOpcaoA());
            jBtalineaB.setText(pergunt.getOpcaoB());
            jBtalineaC.setText(pergunt.getOpcaoC());
            jBtalineaD.setText(pergunt.getOpcaoD());
            jLblPergunta.setText(pergunt.getPergunta());
           }
          jLabelAcertos.setText("Acertos: "+acertos);
          jLabelErros.setText("Erros: "+erros);
           
        jPanel3.repaint();
        jPanel3.validate();
      
      }
      
      public void adicionaIcon(JButton butao){
          
          
      if (jBtalineaA.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (jBtalineaB.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (jBtalineaC.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (jBtalineaD.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
       if (!(butao.getText().equalsIgnoreCase(pergunt.getResposta()))){
          butao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (2).png")));
      }
        jPanel3.repaint();
        jPanel3.validate();
        
        ActionListener acao= new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                if ((butao.getText().equalsIgnoreCase(pergunt.getResposta()))){
                  jProgressBar1.setValue(jProgressBar1.getValue()+10);
                  acertos+=1;
                }else{
                  jProgressBar1.setValue(jProgressBar1.getValue()-10);
                  erros+=1;
                  errosPorNivel+=1;
                }
                    
                    jBtalineaA.setIcon(null);
                    jBtalineaB.setIcon(null);
                    jBtalineaC.setIcon(null);
                    jBtalineaD.setIcon(null);
                    jPanel3.repaint();
                    jPanel3.validate();
                    
                    if(jProgressBar1.getValue()==100){
                       
                        if(nivel.equalsIgnoreCase("superior")){
                            JOptionPane.showMessageDialog(null, "Parabens conpletou o jogo  com  "+erros+"  erros!");
                             jProgressBar1.setValue(0);
                             trocouQuantasVezes=0;
                             podeVoltar= true;
                             nivel = "basico";
                             acertos=0;
                             erros=0;
                             errosPorNivel=0;
                             jBtnVoltarActionPerformed(ev);
                        }else if(nivel.equalsIgnoreCase("medio")){
                            errosPorNivel=0;
                            nivel = "superior";
                             jProgressBar1.setValue(0);
                             trocouQuantasVezes=0;
                        }else if(nivel.equalsIgnoreCase("basico")){
                            errosPorNivel=0;
                            nivel = "medio";
                            jProgressBar1.setValue(0);
                            trocouQuantasVezes=0;
                        }
                        
                        
                    }
                    jLabelNivel.setText("Nivel: "+nivel+"  "+jProgressBar1.getValue()+"%");
                    jLabelCategoria.setText("Categoria:  "+categoria);
                    jPanel3.repaint();
                    jPanel3.validate();
                    prencherLabel();
                    t.stop();
            }
            };
        
        
        t = new Timer(800,acao); 
        t.start();
        
         
      }
      public void temporizador(){
          ActionListener acao = null;
           t = new Timer(800,acao); 
          while (jProgressBar2.getValue()>0) {              
             
             acao= new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                
                 jProgressBar2.setValue(jProgressBar2.getValue()-5);
                 jPanel5.repaint();
                    jPanel5.validate();
              t.stop();
            }
            };
           
        t.start();
              
          }
          
      }
}