/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.perguntas;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.Random;
import java.util.Vector;
import javax.sound.midi.Sequence;
import javax.sound.midi.Sequencer;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author danny
 */
public class Principal1 extends javax.swing.JFrame {
 private static String nivel = "Basico";
 private int processado = 0;
 private int bonus = 0;
 private boolean podeVoltar = true;
private perguntas pergunt ;
private boolean prencherLabel=true;
private Timer t;
private String tipoDoJogo = "novo jogo";
private static java.awt.event.ActionEvent ev;
private String jogador1=JOptionPane.showInputDialog("Digite o nome do Jogador1");
private String jogador2=JOptionPane.showInputDialog("Digite o nome do Jogador2");


Sequence currentSound;
	Sequencer player;
	String songFile;

    /**
     * Creates new form Principal
     */
    public Principal1() {
        initComponents();        
        jLabelJogador1.setText("Jogador1: "+jogador1);
        jLabelJogador2.setText("Jogador2:  "+jogador2);
         jProgressBar2.setValue(50);
        jLabelPerJG1.setText(jProgressBar2.getValue()+"%");
        jLabelPerJG2.setText(jProgressBar2.getValue()+"%");
        }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLblPergunta = new javax.swing.JLabel();
        jBtalineaB2 = new javax.swing.JButton();
        jBtalineaA2 = new javax.swing.JButton();
        jBtalineaC2 = new javax.swing.JButton();
        jBtalineaD2 = new javax.swing.JButton();
        jLabelJogador1 = new javax.swing.JLabel();
        jBtnAjuda2 = new javax.swing.JButton();
        jBtnVoltar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBtalineaB3 = new javax.swing.JButton();
        jBtalineaA3 = new javax.swing.JButton();
        jBtalineaC3 = new javax.swing.JButton();
        jBtalineaD3 = new javax.swing.JButton();
        jLabelJogador2 = new javax.swing.JLabel();
        jLabelPerJG1 = new javax.swing.JLabel();
        jLabelPerJG2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLblPergunta.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLblPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jBtalineaB2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaB2MouseClicked(evt);
            }
        });

        jBtalineaA2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaA2MouseClicked(evt);
            }
        });

        jBtalineaC2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaC2MouseClicked(evt);
            }
        });

        jBtalineaD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaD2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaD2MouseClicked(evt);
            }
        });

        jLabelJogador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelJogador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation-hat-and-diploma.png"))); // NOI18N
        jLabelJogador1.setText("  Jogador1:");

        jBtnAjuda2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnAjuda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help_icon-icons.com_73700.png"))); // NOI18N
        jBtnAjuda2.setText("Ajuda");
        jBtnAjuda2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBtnAjuda2FocusGained(evt);
            }
        });
        jBtnAjuda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAjuda2ActionPerformed(evt);
            }
        });

        jBtnVoltar2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnVoltar2.setText("Voltar");
        jBtnVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltar2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("B:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("A:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("C:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("D:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("B:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("A:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("C:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("D:");

        jBtalineaB3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaB3MouseClicked(evt);
            }
        });

        jBtalineaA3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaA3MouseClicked(evt);
            }
        });

        jBtalineaC3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaC3MouseClicked(evt);
            }
        });

        jBtalineaD3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalineaD3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalineaD3MouseClicked(evt);
            }
        });

        jLabelJogador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelJogador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation-hat-and-diploma.png"))); // NOI18N
        jLabelJogador2.setText("  Jogador2:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAjuda2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabelJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtalineaB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtalineaA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtalineaD2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtalineaC2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtalineaC3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jBtalineaB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtalineaD3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBtalineaA3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabelPerJG1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabelPerJG2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnAjuda2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jBtnVoltar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8))
                    .addComponent(jLabelJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPerJG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPerJG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtalineaA2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtalineaB2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jBtalineaC2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtalineaD2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtalineaA3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtalineaB3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtalineaC3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtalineaD3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jPanel1.add(jPanel5, "card5");
        jPanel5.getAccessibleContext().setAccessibleParent(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltar2ActionPerformed
       Principal p = new Principal();
       p.setVisible(true);
       p.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_jBtnVoltar2ActionPerformed

    private void jBtnAjuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAjuda2ActionPerformed
        JDialog d = new JDialog(new JFrame(),true);
        d.setContentPane(new Ajuda().getContentPane());
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
        
    }//GEN-LAST:event_jBtnAjuda2ActionPerformed

    private void jBtalineaA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaA2MouseClicked
        if(evt.getClickCount()==1){
           adicionaIcon(jBtalineaA2);
        podeVoltar = false; 
        }
    }//GEN-LAST:event_jBtalineaA2MouseClicked

    private void jBtalineaD2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaD2MouseClicked
        if(evt.getClickCount()==1){
            adicionaIcon(jBtalineaD2);
            podeVoltar = false;
        }
    }//GEN-LAST:event_jBtalineaD2MouseClicked

    private void jBtalineaC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaC2MouseClicked
        if(evt.getClickCount()==1){
            adicionaIcon(jBtalineaC2);
            podeVoltar = false;
        }
    }//GEN-LAST:event_jBtalineaC2MouseClicked

    private void jBtalineaB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaB2MouseClicked
         
 
         if(evt.getClickCount()==1){
            adicionaIcon(jBtalineaB2);
            podeVoltar = false;
        }
    }//GEN-LAST:event_jBtalineaB2MouseClicked

    private void jBtnAjuda2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBtnAjuda2FocusGained
       if(prencherLabel){
           prencherLabel();
       }
      prencherLabel=false;       
    }//GEN-LAST:event_jBtnAjuda2FocusGained

    private void jBtalineaB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaB3MouseClicked
         if(evt.getClickCount()==1){
            adicionaIcon(jBtalineaB3);
            podeVoltar = false;
        }
    }//GEN-LAST:event_jBtalineaB3MouseClicked

    private void jBtalineaA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaA3MouseClicked
        if(evt.getClickCount()==1){
            adicionaIcon(jBtalineaA3);
            podeVoltar = false;
        }
    }//GEN-LAST:event_jBtalineaA3MouseClicked

    private void jBtalineaC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaC3MouseClicked
         if(evt.getClickCount()==1){
            adicionaIcon(jBtalineaC3);
            podeVoltar = false;
        }
    }//GEN-LAST:event_jBtalineaC3MouseClicked

    private void jBtalineaD3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalineaD3MouseClicked
         if(evt.getClickCount()==1){
            adicionaIcon(jBtalineaD3);
            podeVoltar = false;
        }
    }//GEN-LAST:event_jBtalineaD3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         String tema2="com.jtattoo.plaf.noire.NoireLookAndFeel";
         String tema5="com.jtattoo.plaf.mint.MintLookAndFeel";
         String tema9="com.jtattoo.plaf.acryl.AcrylLookAndFeel";
         String tema10="com.jtattoo.plaf.hifi.HiFiLookAndFeel";
         String tema13="com.jtattoo.plaf.fast.FastLookAndFeel";
         String tema14="com.jtattoo.plaf.graphite.GraphiteLookAndFeel";
        try {
            UIManager.setLookAndFeel(tema14);
        } catch (Exception e) {

        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

       /* Create and display the form */
 
 
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtalineaA2;
    private javax.swing.JButton jBtalineaA3;
    private javax.swing.JButton jBtalineaB2;
    private javax.swing.JButton jBtalineaB3;
    private javax.swing.JButton jBtalineaC2;
    private javax.swing.JButton jBtalineaC3;
    private javax.swing.JButton jBtalineaD2;
    private javax.swing.JButton jBtalineaD3;
    private javax.swing.JButton jBtnAjuda2;
    private javax.swing.JButton jBtnVoltar2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelJogador1;
    private javax.swing.JLabel jLabelJogador2;
    private javax.swing.JLabel jLabelPerJG1;
    private javax.swing.JLabel jLabelPerJG2;
    private javax.swing.JLabel jLblPergunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

         
      public perguntas atualizaPergunta() {
          Random gerador = new Random();
          Vector<perguntas> lerObject = null;
          perguntas pergunta ;
        try {
            FileInputStream arquivo = new FileInputStream("perguntas.arq");
            ObjectInputStream objecto = new ObjectInputStream(arquivo);
            lerObject = (Vector<perguntas>) objecto.readObject();
            arquivo.close();
            objecto.close();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null," Erro de Leitura da Pergunta: "+erro.getMessage());   
        }
        pergunta = lerObject.get(gerador.nextInt(lerObject.size()));
        //if(pergunta.getCategoria().equalsIgnoreCase("Cultura Geral")&pergunta.getNivel().equalsIgnoreCase(nivel)){
        return pergunta;
       // }
     //return atualizaPergunta();

    }
      
      
      public  void prencherLabel(){
       
          pergunt = atualizaPergunta();
           Random gerador = new Random();
           int n = gerador.nextInt(4);
            
           if(n==0){
            jBtalineaA2.setText(pergunt.getOpcaoD());
            jBtalineaB2.setText(pergunt.getOpcaoA());
            jBtalineaC2.setText(pergunt.getOpcaoB());
            jBtalineaD2.setText(pergunt.getOpcaoC());
            jBtalineaA3.setText(pergunt.getOpcaoD());
            jBtalineaB3.setText(pergunt.getOpcaoA());
            jBtalineaC3.setText(pergunt.getOpcaoB());
            jBtalineaD3.setText(pergunt.getOpcaoC());
            jLblPergunta.setText(pergunt.getPergunta());
           }
           if(n==1){
            jBtalineaA2.setText(pergunt.getOpcaoA());
            jBtalineaB2.setText(pergunt.getOpcaoD());
            jBtalineaC2.setText(pergunt.getOpcaoB());
            jBtalineaD2.setText(pergunt.getOpcaoC());
            jBtalineaA3.setText(pergunt.getOpcaoA());
            jBtalineaB3.setText(pergunt.getOpcaoD());
            jBtalineaC3.setText(pergunt.getOpcaoB());
            jBtalineaD3.setText(pergunt.getOpcaoC());
            jLblPergunta.setText(pergunt.getPergunta());
           }
           if(n==2){
            jBtalineaA2.setText(pergunt.getOpcaoA());
            jBtalineaB2.setText(pergunt.getOpcaoB());
            jBtalineaC2.setText(pergunt.getOpcaoD());
            jBtalineaD2.setText(pergunt.getOpcaoC());
            jBtalineaA3.setText(pergunt.getOpcaoA());
            jBtalineaB3.setText(pergunt.getOpcaoB());
            jBtalineaC3.setText(pergunt.getOpcaoD());
            jBtalineaD3.setText(pergunt.getOpcaoC());
            jLblPergunta.setText(pergunt.getPergunta());
           }
           if(n==3){
            jBtalineaA2.setText(pergunt.getOpcaoA());
            jBtalineaB2.setText(pergunt.getOpcaoB());
            jBtalineaC2.setText(pergunt.getOpcaoC());
            jBtalineaD2.setText(pergunt.getOpcaoD());
            jBtalineaA3.setText(pergunt.getOpcaoA());
            jBtalineaB3.setText(pergunt.getOpcaoB());
            jBtalineaC3.setText(pergunt.getOpcaoC());
            jBtalineaD3.setText(pergunt.getOpcaoD());
            jLblPergunta.setText(pergunt.getPergunta());
           }
          
           
        jPanel5.repaint();
        jPanel5.validate();
          
      }
      
      public void adicionaIcon(JButton butao){
         if (butao==jBtalineaA3||butao==jBtalineaB3||butao==jBtalineaC3||butao==jBtalineaD3){
                  if (jBtalineaA3.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (jBtalineaB3.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (jBtalineaC3.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (jBtalineaD3.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (!(butao.getText().equalsIgnoreCase(pergunt.getResposta()))){
          butao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (2).png")));
      }
         }
           if (butao==jBtalineaA2||butao==jBtalineaB2||butao==jBtalineaC2||butao==jBtalineaD2){
        if (jBtalineaA2.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (jBtalineaB2.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (jBtalineaC2.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (jBtalineaD2.getText().equalsIgnoreCase(pergunt.getResposta())){
          jBtalineaD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (1).png")));
      }
      if (!(butao.getText().equalsIgnoreCase(pergunt.getResposta()))){
          butao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/correto (2).png")));
      }
         }
          
         
      
      
      
       
        jPanel5.repaint();
        jPanel5.validate();
        
         ActionListener acao= new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
        
        
         if ((butao.getText().equalsIgnoreCase(pergunt.getResposta()))){
             if (butao==jBtalineaA2||butao==jBtalineaB2||butao==jBtalineaC2||butao==jBtalineaD2){
                 jProgressBar2.setValue(jProgressBar2.getValue()+5);
             }
             if (butao==jBtalineaA3||butao==jBtalineaB3||butao==jBtalineaC3||butao==jBtalineaD3){
                 jProgressBar2.setValue(jProgressBar2.getValue()-5);
             }
                  
                 }else{
              if (butao==jBtalineaA2||butao==jBtalineaB2||butao==jBtalineaC2||butao==jBtalineaD2){
                 jProgressBar2.setValue(jProgressBar2.getValue()-5);
             }
                 if (butao==jBtalineaA3||butao==jBtalineaB3||butao==jBtalineaC3||butao==jBtalineaD3){
                 jProgressBar2.setValue(jProgressBar2.getValue()+5);
             }
                }
             
        jLabelPerJG1.setText(jProgressBar2.getValue()+"%");
        jLabelPerJG2.setText(100-jProgressBar2.getValue()+"%");
                    jBtalineaA3.setIcon(null);
                    jBtalineaB3.setIcon(null);
                    jBtalineaC3.setIcon(null);
                    jBtalineaD3.setIcon(null);
                    jBtalineaA2.setIcon(null);
                    jBtalineaB2.setIcon(null);
                    jBtalineaC2.setIcon(null);
                    jBtalineaD2.setIcon(null);
                    jPanel5.repaint();
                    jPanel5.validate();
                    
                    if(jProgressBar2.getValue()==100){
                            JOptionPane.showMessageDialog(null,jogador1 + " Ganha o Jogo!");
                             jProgressBar2.setValue(50);
                            
                        }
                    if(jProgressBar2.getValue()==0){
                            JOptionPane.showMessageDialog(null,jogador2 + " Ganha o Jogo!");
                             jProgressBar2.setValue(50);
                          
                        }
        
                    jPanel5.repaint();
                    jPanel5.validate();
                    prencherLabel();
                       t.stop();
            }
            };
                    
                     t = new Timer(800,acao); 
        t.start();
           
      }
      public void temporizador(){
          ActionListener acao = null;
           t = new Timer(800,acao); 
          while (jProgressBar2.getValue()>0) {              
             
             acao= new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                
                 jProgressBar2.setValue(jProgressBar2.getValue()-5);
                 jPanel5.repaint();
                    jPanel5.validate();
              t.stop();
            }
            };
           
        t.start();
              
          }
          
      }
}